source 'https://github.com/KivinSun/STESpecs.git'
source 'https://github.com/CocoaPods/Specs.git'


use_frameworks!

platform :ios, '8.0'

target 'STEAuthorKit_Example' do
  pod 'STEAuthorKit', :path => '../'

  target 'STEAuthorKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
